name: Imagenes
rules:
  - image: caramelo1.png
    when:
      black: 0
      blue: 1
      green: 0
      red: 0
  - image: caramelo2.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 0
  - image: caramelo3.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 1
  - image: caramelo4.png
    when:
      black: 0
      blue: 1
      green: 1
      red: 0
  - image: images.png
    when:
      black: 2
      blue: 0
      green: 0
      red: 0
  - image: estrella.png
    when:
      black: 3
      blue: 0
      green: 0
      red: 0
  - image: flechas.png
    when:
      black: 0
      blue: 1
      green: 0
      red: 0
